### ISSUE TITLE
Advanced Archiving Guide is inaccessible

### ISSUE THREAD

**Issue by PaulFidika** [ArweaveTeam/docs.arweave.org-info#11]
This document cannot be viewed publicly:

https://docs.arweave.org/info/~/drafts/-LZ4Kf6u9bkaNsVo7ija/archiving/archiving-web-pages

It is linked to at the bottom of this document:

https://docs.arweave.org/info/archiving/step-by-step-beginners-guide

Could someone make that document publicly available? If it is semi-complete, thanks.

**Comment by rosmcmahon** [comment]
appears fixed now, thanks!
![image](https://user-images.githubusercontent.com/1430130/147914189-c1c7d15c-9f0b-40b9-a544-5060121d0575.png)
