### ISSUE TITLE
Slash is missing in documentation

### ISSUE THREAD

**Issue by aahutsal** [ArweaveTeam/docs.arweave.org-info#8]
![image](https://user-images.githubusercontent.com/1643117/113473230-ea1dc680-9470-11eb-8fcf-e81397377467.png)

**Comment by blaisep** [comment]
@aahutsal , do you have a link to this or some more context ?

**Comment by blaisep** [comment]
@aahutsal , this *is* the wrong repo.

The problem is in:
https://github.com/ArweaveTeam/docs.arweave.org-developers/blob/master/server/http-api.md#blocks

**Comment by ririen** [comment]
PR was approved: https://github.com/ArweaveTeam/docs.arweave.org-developers/pull/17

Issue to be closed @blaisep  :)
