### ISSUE TITLE
where ar files path?

### ISSUE THREAD

**Issue by alexpebody** [ArweaveTeam/docs.arweave.org-info#9]
hello, please need help, some days ago i has miner in windows 10 and i have mane TB data of .ar files, now i has install ubuntu 20.04 and i can't find where i must set path to my .ar files?

thank you so much!

**Comment by rosmcmahon** [comment]
hi @alexpebody 
this question does not appear to be regarding the official Arweave miner, or regarding the documentation here, and either way support for your individual system can be found in the Discord server.
There are channels for the 3 known public pool miners in the [Arweave Miners discord](https://discord.gg/nk8cqkxf) Perhaps you should ask in one of those. thanks!
